/*
 * Copyright (c) 2024 Alif Semiconductor
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALIF_MAC154_DEF_H_
#define ALIF_MAC154_DEF_H_

/**
 * Status codes
 */
enum alif_mac154_status_code {
	ALIF_MAC154_STATUS_OK = 0,
	ALIF_MAC154_STATUS_NO_ACK,
	ALIF_MAC154_STATUS_CHANNEL_ACCESS_FAILURE,
	ALIF_MAC154_STATUS_INVALID_STATE,
	ALIF_MAC154_STATUS_INVALID_MESSAGE,
	ALIF_MAC154_STATUS_HW_FAILED,
	ALIF_MAC154_STATUS_SW_FAILED,
	ALIF_MAC154_STATUS_FAILED,
	ALIF_MAC154_STATUS_COMM_FAILURE,
	ALIF_MAC154_STATUS_OUT_OF_SYNC,
	ALIF_MAC154_STATUS_ABORT,
	ALIF_MAC154_STATUS_RESET,
	ALIF_MAC154_STATUS_RX_STOPPED,
};

/**
 * CCA mode
 */
enum alif_mac154_cca_mode {
	ALIF_MAC154_CCA_MODE_ED = 0,
	ALIF_MAC154_CCA_MODE_CS,
	ALIF_MAC154_CCA_MODE_ED_OR_CS,
	ALIF_MAC154_CCA_MODE_ED_AND_CS,
};

#endif /* ALIF_MAC154_DEF_H_ */
